version: 2.1
orbs:
  # orbs contain basc recipes and reproducible actions (install node, aws, etc.)
  node: circleci/node@5.0.2
  eb: circleci/aws-elastic-beanstalk@2.0.1
  aws-cli: circleci/aws-cli@3.1.1

jobs:
  build-deploy:
    docker:
      # the base image can run most needed actions with orbs
      - image: "cimg/node:14.15"
    steps:
      # install node and checkout code
      - node/install:
          node-version: '14.15'
      - eb/setup
      - aws-cli/setup       
      - checkout
      #Installing dependencies in the the frontend #DONE  
      - run:
          name: Install Front-End Dependencies
          command: |
            echo "NODE --version" 
            echo $(node --version)
            echo "NPM --version" 
            echo $(npm --version)
            npm run frontend:install
      #Installing dependencies in the the backend API #DONE       
      - run:
          name: Install API Dependencies
          command: |
            npm run api:install
      #Lint the frontend #DONE
      - run:
          name: Front-End Lint
          command: |
            npm run frontend:lint
      #Building the frontend app #DONE
      - run:
          name: Front-End Build
          command: |
            npm run frontend:build
      #Building the backend API #DONE   
      - run:
          name: API Build
          command: |
            npm run api:build
            npm run api:env
            npm run api:zip
      #Deploying the back-endto EB and the front-end to S3
      - run:
          name: Deploy the back-end and the front-end
          command: |
            npm run api:ebenv
            npm run api:deploy
            npm run frontend:deploy

            
workflows:
  udagram:
    jobs:
      - build-deploy:
          filters:
            branches:
              only:
                - master